# suppress inspection "UnusedProperty" for whole file

# Copyright (C) 2016 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# ----------------------------------------------------------------------------------------------------------------------
# G r a d l e
# ----------------------------------------------------------------------------------------------------------------------
# https://docs.gradle.org/current/userguide/build_environment.html#gradle_properties_reference

version=2026.4.1

# default: -Xmx512m -XX:MaxMetaspaceSize=256m
# max. Heap: 2 GB (ggf. reduzieren)
# min. Heap: 1 GB (ggf. reduzieren)
# Metadaten: max. 512 MB statt unbegrenzt
# https://docs.gradle.org/current/userguide/config_gradle.html#sec:configuring_jvm_memory
# https://www.baeldung.com/jvm-parameters
# https://docs.gradle.org/current/userguide/best_practices_performance.html#use_utf8_encoding
org.gradle.jvmargs=-Xmx2g -Xms1g -XX:MaxMetaspaceSize=512m -Djava.awt.headless=true -Dfile.encoding=UTF-8

# https://docs.gradle.org/current/userguide/best_practices_performance.html#use_build_cache
# ${env:USERPROFILE}\.gradle\caches\build-cache-*
org.gradle.caching=true
# https://docs.gradle.org/current/userguide/best_practices_performance.html#use_configuration_cache
# TODO Tasks "bootJar" und "dependencyUpdates" rufen "Task.project" auf: nicht unterstuetzt mit "configuration cache"
#org.gradle.configuration-cache=true
org.gradle.kotlin.dsl.allWarningsAsErrors=true
#org.gradle.parallel=true
org.gradle.warning.mode=all

#javaLanguageVersion=26
#javaLanguageVersionJavadoc=26
#javaLanguageVersionSonar=26
org.gradle.java.installations.fromEnv=GRADLE_TOOLCHAIN

# ----------------------------------------------------------------------------------------------------------------------
# J a v a
# ----------------------------------------------------------------------------------------------------------------------
enablePreview=true
#mapStructVerbose=true

# ----------------------------------------------------------------------------------------------------------------------
# S p r i n g   M o d u l e   u n d   K o n f i g u r a t i o n
# ----------------------------------------------------------------------------------------------------------------------
#persistence=false
#mail=false
security=false

observability=false
graphql=false
webclient=false
openapi=false

activeProfiles=dev
#activeProfiles=dev,http
#activeProfiles=locust
#devTools=false

# ----------------------------------------------------------------------------------------------------------------------
# C l o u d   N a t i v e   B u i l d p a c k s
# ----------------------------------------------------------------------------------------------------------------------
#imagePath=juergenzimmermann

# "paketobuildpacks/builder-noble-java-tiny" enthaelt keine Shell
#paketoBuilder=paketobuildpacks/builder-noble-java-tiny
#paketoBuilder=paketobuildpacks/builder-jammy-java-tiny
#paketoBuilder=paketobuildpacks/builder-jammy-base

# Image mit bash statt ohne Shell (bei paketobuildpacks/ubuntu-noble-run-tiny oder paketobuildpacks/builder-jammy-java-tiny)
# https://docs.spring.io/spring-boot/gradle-plugin/packaging-oci-image.html#build-image.examples.custom-image-builder
#paketoRunImage=paketobuildpacks/ubuntu-noble-run-tiny
#paketoRunImage=paketobuildpacks/ubuntu-noble-run-base
#paketoRunImage=paketobuildpacks/run-jammy-base

#javaLanguageVersionBuildpacks=26

# Default Buildpack: Bellsoft Liberica mit JRE 8, 11, 17, 21 (default), 25, 26
# Azul Zulu: JRE 8, 11, 17, 21 (default), 25, 26
#buildpack=azul-zulu
# Eclipse Temurin: JRE 8, 11, 17, 21 (default), 25
#buildpack=adoptium
# SapMachine: JRE 11, 17, 21 (default), 25
#buildpack=sap-machine

# ----------------------------------------------------------------------------------------------------------------------
# D a t e n b a n k
# ----------------------------------------------------------------------------------------------------------------------
spring.datasource.username=gastronomie
spring.datasource.password=p
# https://jdbc.postgresql.org/documentation/ssl
spring.datasource.url=jdbc:postgresql://localhost/gastronomie?sslmode=verify-ca&sslrootcert=/Users/abdullah/IdeaProjects/kunde-v2/kunde/extras/compose/postgres/init/tls/server.crt
#spring.datasource.url=jdbc:postgresql://localhost/kunde
spring.flyway.tablespace=gastronomiespace
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
spring.flyway.clean-disabled=false

# ----------------------------------------------------------------------------------------------------------------------
# K e y c l o a k
# ----------------------------------------------------------------------------------------------------------------------
# Konfiguration des "HTTP Clients" fuer Spring zur REST-Schnittstelle von Keycloak, um z.B. einen Token anzufordern
# TODO Integrationstests mit Zertifikat fuer Keycloak mit HTTPS
app.keycloak.client-secret=MuRe9y9AuuqqYwG2QfVRPKC48A3G91Wg
##app.keycloak.issuer-uri=https://localhost:8843/realms/spring
#app.keycloak.issuer-uri=http://localhost:8880/realms/spring
#
## fuer SecurityConfig.keycloakRepository()
app.keycloak.host=localhost
##app.keycloak.schema=https
app.keycloak.schema=http
##app.keycloak.port=8843
app.keycloak.port=8880

# ----------------------------------------------------------------------------------------------------------------------
# S o n a r Q u b e
# ----------------------------------------------------------------------------------------------------------------------
sonarToken=sqa_d9f53fa0cafbdb51f00d74b3eaf71c6f323004cb

# ----------------------------------------------------------------------------------------------------------------------
# O W A S P   D e p e n d e n c y   C h e c k
# ----------------------------------------------------------------------------------------------------------------------
# https://nvd.nist.gov/developers/request-an-api-key
nvdApiKey=47fbc0a4-9240-4fda-9a26-d7d5624c16bf
#depCheckDataDirectory=C:/Zimmermann/dependency-check-data

# ----------------------------------------------------------------------------------------------------------------------
# T e s t s   m i t   J U n i t
# ----------------------------------------------------------------------------------------------------------------------
#test=all
#test=integration
#test=rest
#test=rest-get
#test=rest-write
#test=graphql
#test=query
#test=mutation
#test=unit
#test=service-read
#test=service-write

#showTestStandardStreams=true
